spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: hikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 1800000
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.learn.seckill.pojo

logging:
  level:
    com.learn.seckill.mapper: debug